name: CI
on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
     - run: npm install
     - run: npm test
       env:
          CONNECT_STRING: ${{ secrets.TEST_DB_SECRET }}
